### ISSUE TITLE
[VSDIA-COMPONENT] Move DELETE PROJECT and CARD SETTING to UI, for use on planner

### ISSUE THREAD

**Issue by iguoliveira** [ets-einer/einer#120]
Need to move 'DeleteProjectModal' and 'CardSetting' component to UI

Planner needs to use it to mantain same visual identity

All these components are in VsDia

**Comment by viniciusventura29** [comment]
I just already resolved this! I am waiting the  approvement of my pull request to merge to dev. 👍🏻
