### ISSUE TITLE
Cadastro de usuário iniciando com email falhando

### ISSUE THREAD

**Issue by viktormarinho** [ets-einer/einer#190]
**Describe the bug**
Quando um admin cria um user e coloca um email para ele, o usuário ainda assim vem com o email placeholder de quem não possui email ainda (XXXXXXX@seuEmail.com)

Aconteceu na branch da pr #187  (welcome modal ventura)
mas acho que está na dev tbm

**Comment by viniciusventura29** [comment]
I just already fixed it in the "Fixing excel modal" pull request.
